language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - git clone https://github.com/NixOS/patchelf
  - pushd patchelf
  - ./bootstrap.sh
  - ./configure && make
  - sudo make install
  - popd
install:
  - python setup.py install
  - pip install -r dev_requirements.txt
script: nosetests --with-coverage --cover-package=elfrewriter elfrewriter

notifications:
  email:
    recipients:
      - davidc@enthought.com
    on_success: change
    on_failure: always
